In [ ]:
# Text Classification

In [ ]:
import csv
input_file= "symptoms_all.csv"
output_file="symptoms_all_variables.csv"
with open(input_file, 'r') as csvfile:
    with open(output_file, 'w', newline='') as f:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            need = [row[0], row[8],row[22],row[25],row[37],row[45],row[47],row[64],row[101], row[116], row[253], row[280]]
            len_need = len(need)
            for i in range(len_need):
                if need[i] == '':
                   need[i] = "0"
                elif need[i] == 'y':
                   need[i] = "1"
                else:
                   continue

            if need[0] == 'y':
               need[0] = "1"
            #print(need)



            thewriter = csv.writer(f)
            thewriter.writerow(need)
            #f.write("%s %s %s %s %s %s %s %s %s %s %s\n" %(need[8],need[22],need[25],need[37],need[45],need[47],need[64],need[101], need[116], need[248], need[279]))

In [ ]:
pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in /home/vmuser/anaconda3/lib/python3.6/site-packages (2.6.2)
Requirement already satisfied: flatbuffers~=1.12.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.12)
Requirement already satisfied: keras<2.7,>=2.6.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (2.6.0)
Requirement already satisfied: wrapt~=1.12.1 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: typing-extensions~=3.7.4 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (3.7.4.3)
Requirement already satisfied: numpy~=1.19.2 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.19.5)
Requirement already satisfied: grpcio<2.0,>=1.37.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.39.0)
Requirement already satisfied: absl-py~=0.10 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (0.13.0)
Requirement already satisfied: google-pasta~=0.2 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: astunparse~=1.6.3 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: protobuf>=3.9.2 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (3.17.3)
Requirement already satisfied: six~=1.15.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: termcolor~=1.1.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: wheel~=0.35 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: gast==0.4.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (0.4.0)
Requirement already satisfied: opt-einsum~=3.3.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: tensorboard<2.7,>=2.6.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (2.6.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: tensorflow-estimator<2.7,>=2.6.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (2.6.0)
Requirement already satisfied: clang~=5.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (5.0)
Requirement already satisfied: h5py~=3.1.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: cached-property in /home/vmuser/anaconda3/lib/python3.6/site-packages (from h5py~=3.1.0->tensorflow) (1.5.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (57.2.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (0.12.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (1.8.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (1.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (2.26.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (0.6.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (0.4.4)
Requirement already satisfied: markdown>=2.6.8 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow) (3.3.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow) (1.3.0)
Requirement already satisfied: importlib-metadata in /home/vmuser/anaconda3/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow) (4.6.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow) (0.4.8)
Requirement already satisfied: idna<4,>=2.5 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (2.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (2017.7.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow) (1.22)
Requirement already satisfied: oauthlib>=3.0.0 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow) (3.1.1)
Requirement already satisfied: zipp>=0.5 in /home/vmuser/anaconda3/lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow) (3.5.0)
WARNING: You are using pip version 21.2.1; however, version 21.3.1 is available.
You should consider upgrading via the '/home/vmuser/anaconda3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import numpy as np
import pandas as pd
from sklearn import metrics
from patsy import dmatrices
import statsmodels.api as sm
from keras import models
from keras import layers
from keras.layers import Dense
from keras.models import Model
import matplotlib.pyplot as plt
from keras.layers import Dropout
from keras.layers import Flatten
from tensorflow.keras.optimizers import SGD
from keras.layers import Flatten
from nltk.corpus import stopwords
from sklearn import datasets, svm
from keras.models import Sequential
from keras.layers import Embedding
from pandas import Series, DataFrame
from keras.layers import MaxPooling1D
from gensim.models import KeyedVectors
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import SGDClassifier
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from statsmodels.nonparametric import smoothers_lowess
from keras.preprocessing.sequence import pad_sequences
from statsmodels.nonparametric.kde import KDEUnivariate
from keras.layers import Conv1D, GlobalMaxPooling1D, Conv2D, MaxPooling2D
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve
from sklearn.naive_bayes import MultinomialNB

import re
import nltk
import gensim
import logging
import bs4 as bs
import urllib.request
import xgboost as xgb
import multiprocessing
import texthero as hero
from gensim import utils
from sklearn import utils
from hyperas import optim
from tqdm import tqdm
tqdm.pandas(desc="progress-bar")
from gensim.models import Doc2Vec
from nltk.corpus import stopwords
from xgboost import XGBClassifier
from nltk.stem import SnowballStemmer
from sklearn.metrics import accuracy_score
from hyperopt import Trials, STATUS_OK, tpe
from gensim.models.doc2vec import TaggedDocument
from hyperas.distributions import choice, uniform
from gensim.models.doc2vec import LabeledSentence
from sklearn.linear_model import LogisticRegression
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_classification

from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score, make_scorer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import sent_tokenize, word_tokenize

dataset = pd.read_csv(output_file)
dataset

,Id,female,tuber,diabetes,men_con,cough,ch_cough,diarr,exc_urine,exc_drink,disease_description,finaldiagnosis
0,100018,0,1,0,0,1,1,0,0,1,The deceased developed blisters under the righ...,0.0
1,100078,1,0,0,0,1,1,1,0,0,At first the deceased was complaining about br...,0.0
2,100096,1,1,0,0,1,1,0,0,1,She was complaining about hot feet with swelli...,0.0
3,100101,1,0,0,0,0,0,0,0,0,At first deceased complained headache and stom...,0.0
4,100108,0,0,0,1,0,0,0,0,1,Beginning of illness deceased dreamed eating f...,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8693,631156,1,0,0,0,0,0,0,0,0,She started by complaining with headache and a...,0.0
8694,632743,0,0,0,0,0,0,0,0,0,0,0.0
8695,633179,1,0,0,0,0,0,0,0,0,The deceased started by having painful abdomen...,0.0
8696,633559,0,0,0,0,0,0,0,0,0,0,0.0
8697,633713,1,0,0,0,0,0,0,0,0,She was found dead in the morning.,0.0

In [ ]:
dataset = pd.read_csv("NewVA.csv")
dataset

,female,tuber,diabetes,men_con,cough,ch_cough,diarr,exc_urine,exc_drink,disease_description,finaldiagnosis
0,0,1,0,0,1,1,0,0,1,The deceased developed blisters under the righ...,0
1,1,0,0,0,1,1,1,0,0,At first the deceased was complaining about br...,0
2,1,1,0,0,1,1,0,0,1,She was complaining about hot feet with swelli...,0
3,1,0,0,0,0,0,0,0,0,At first deceased complained headache and stom...,0
4,0,0,0,1,0,0,0,0,1,Beginning of illness deceased dreamed eating f...,0
...,...,...,...,...,...,...,...,...,...,...,...
7828,1,1,0,1,1,1,1,0,0,"She started by coughing, fever and have diarrh...",0
7829,1,0,0,0,1,0,0,0,0,The deceased started by coughing where she was...,0
7830,1,0,0,0,0,0,0,0,0,She started by complaining with headache and a...,0
7831,1,0,0,0,0,0,0,0,0,The deceased started by having painful abdomen...,0
7832,1,0,0,0,0,0,0,0,0,She was found dead in the morning.,0

In [ ]:
dataset3 = dataset.drop("disease_description", axis = 1)
dataset3

,female,tuber,diabetes,men_con,cough,ch_cough,diarr,exc_urine,exc_drink,finaldiagnosis
0,0,1,0,0,1,1,0,0,1,0
1,1,0,0,0,1,1,1,0,0,0
2,1,1,0,0,1,1,0,0,1,0
3,1,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
7828,1,1,0,1,1,1,1,0,0,0
7829,1,0,0,0,1,0,0,0,0,0
7830,1,0,0,0,0,0,0,0,0,0
7831,1,0,0,0,0,0,0,0,0,0
7832,1,0,0,0,0,0,0,0,0,0

In [ ]:
y3 = dataset3["finaldiagnosis"]

In [ ]:
import numpy as np
numpy3 = np.load('VAUnbert.npy')
numpy3.shape

(7833, 768)

In [ ]:
#Coverting a numpy array into a data frame
df = pd.DataFrame(numpy3)
df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.075627,0.132981,0.128455,0.905081,0.991933,0.882216,0.631269,0.180067,-0.092080,0.405289,...,0.086050,0.911581,-0.854586,0.648514,0.882056,0.490923,-0.781812,-0.398814,-0.883501,-0.442142
1,0.874110,-0.512967,0.025296,-0.966775,-0.214251,-0.715966,-0.707653,0.833488,0.349612,-0.205862,...,-0.409567,-0.831409,0.462622,0.314237,0.653831,0.257510,-0.805141,-0.339686,0.416634,0.151783
2,0.698588,0.467158,0.410709,-0.810982,0.029012,0.067626,-0.181474,0.864893,-0.171834,-0.932124,...,-0.894625,-0.784692,0.330545,-0.783493,0.477859,0.494536,-0.817453,0.619266,0.611336,-0.087373
3,0.549374,-0.087779,0.800487,0.114196,-0.419980,-0.460071,-0.542703,0.911329,-0.320412,-0.951281,...,-0.857571,-0.649075,-0.422010,0.320293,0.490858,0.268078,-0.662021,0.235697,-0.013814,-0.249511
4,0.857971,-0.819153,0.020909,-0.989702,-0.163710,-0.552804,-0.746518,0.656542,0.399067,0.645334,...,-0.055571,-0.858617,0.422339,-0.150346,0.591782,0.317968,-0.539443,-0.302800,0.774663,0.084319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7828,0.552922,-0.030437,0.705118,-0.725346,-0.257711,-0.693921,-0.565398,0.915197,0.452489,-0.804668,...,-0.911566,-0.753274,-0.084145,-0.484399,0.268475,0.410147,-0.594288,0.591290,-0.242765,-0.188511
7829,0.895895,-0.653593,-0.020826,-0.981458,-0.152704,-0.549552,-0.688950,0.846517,0.389257,-0.101193,...,0.097021,-0.765114,0.484713,0.046832,0.555670,0.067885,-0.759208,-0.306088,0.297535,0.296566
7830,0.843698,-0.749100,0.280108,-0.993174,-0.451919,-0.503397,-0.541013,0.661341,0.633278,0.213232,...,-0.274688,-0.641834,0.553275,0.042796,0.577361,0.525815,-0.402874,-0.080782,0.228377,-0.137405
7831,0.782707,-0.670501,-0.326957,-0.994221,-0.277875,-0.670175,-0.670645,0.747636,0.548301,0.354116,...,0.185384,-0.876752,0.563466,0.137789,0.459504,0.385256,-0.566692,-0.363740,0.350959,0.175493
7832,0.744679,0.004101,0.444200,-0.697975,0.361724,-0.459923,-0.141900,0.974487,0.440359,-0.873953,...,-0.803021,-0.897368,-0.108110,-0.015679,-0.186226,0.234440,-0.650007,0.236022,0.451496,-0.114856

In [ ]:
x5 = pd.concat([df,y3], axis = 1)
x5

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,finaldiagnosis
0,0.075627,0.132981,0.128455,0.905081,0.991933,0.882216,0.631269,0.180067,-0.092080,0.405289,...,0.911581,-0.854586,0.648514,0.882056,0.490923,-0.781812,-0.398814,-0.883501,-0.442142,0
1,0.874110,-0.512967,0.025296,-0.966775,-0.214251,-0.715966,-0.707653,0.833488,0.349612,-0.205862,...,-0.831409,0.462622,0.314237,0.653831,0.257510,-0.805141,-0.339686,0.416634,0.151783,0
2,0.698588,0.467158,0.410709,-0.810982,0.029012,0.067626,-0.181474,0.864893,-0.171834,-0.932124,...,-0.784692,0.330545,-0.783493,0.477859,0.494536,-0.817453,0.619266,0.611336,-0.087373,0
3,0.549374,-0.087779,0.800487,0.114196,-0.419980,-0.460071,-0.542703,0.911329,-0.320412,-0.951281,...,-0.649075,-0.422010,0.320293,0.490858,0.268078,-0.662021,0.235697,-0.013814,-0.249511,0
4,0.857971,-0.819153,0.020909,-0.989702,-0.163710,-0.552804,-0.746518,0.656542,0.399067,0.645334,...,-0.858617,0.422339,-0.150346,0.591782,0.317968,-0.539443,-0.302800,0.774663,0.084319,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7828,0.552922,-0.030437,0.705118,-0.725346,-0.257711,-0.693921,-0.565398,0.915197,0.452489,-0.804668,...,-0.753274,-0.084145,-0.484399,0.268475,0.410147,-0.594288,0.591290,-0.242765,-0.188511,0
7829,0.895895,-0.653593,-0.020826,-0.981458,-0.152704,-0.549552,-0.688950,0.846517,0.389257,-0.101193,...,-0.765114,0.484713,0.046832,0.555670,0.067885,-0.759208,-0.306088,0.297535,0.296566,0
7830,0.843698,-0.749100,0.280108,-0.993174,-0.451919,-0.503397,-0.541013,0.661341,0.633278,0.213232,...,-0.641834,0.553275,0.042796,0.577361,0.525815,-0.402874,-0.080782,0.228377,-0.137405,0
7831,0.782707,-0.670501,-0.326957,-0.994221,-0.277875,-0.670175,-0.670645,0.747636,0.548301,0.354116,...,-0.876752,0.563466,0.137789,0.459504,0.385256,-0.566692,-0.363740,0.350959,0.175493,0
7832,0.744679,0.004101,0.444200,-0.697975,0.361724,-0.459923,-0.141900,0.974487,0.440359,-0.873953,...,-0.897368,-0.108110,-0.015679,-0.186226,0.234440,-0.650007,0.236022,0.451496,-0.114856,0

In [ ]:
data = x5.replace("#NULL!",np.NAN)

In [ ]:
data1 = data.replace(np.NAN,-1)
data1

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,finaldiagnosis
0,0.075627,0.132981,0.128455,0.905081,0.991933,0.882216,0.631269,0.180067,-0.092080,0.405289,...,0.911581,-0.854586,0.648514,0.882056,0.490923,-0.781812,-0.398814,-0.883501,-0.442142,0
1,0.874110,-0.512967,0.025296,-0.966775,-0.214251,-0.715966,-0.707653,0.833488,0.349612,-0.205862,...,-0.831409,0.462622,0.314237,0.653831,0.257510,-0.805141,-0.339686,0.416634,0.151783,0
2,0.698588,0.467158,0.410709,-0.810982,0.029012,0.067626,-0.181474,0.864893,-0.171834,-0.932124,...,-0.784692,0.330545,-0.783493,0.477859,0.494536,-0.817453,0.619266,0.611336,-0.087373,0
3,0.549374,-0.087779,0.800487,0.114196,-0.419980,-0.460071,-0.542703,0.911329,-0.320412,-0.951281,...,-0.649075,-0.422010,0.320293,0.490858,0.268078,-0.662021,0.235697,-0.013814,-0.249511,0
4,0.857971,-0.819153,0.020909,-0.989702,-0.163710,-0.552804,-0.746518,0.656542,0.399067,0.645334,...,-0.858617,0.422339,-0.150346,0.591782,0.317968,-0.539443,-0.302800,0.774663,0.084319,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7828,0.552922,-0.030437,0.705118,-0.725346,-0.257711,-0.693921,-0.565398,0.915197,0.452489,-0.804668,...,-0.753274,-0.084145,-0.484399,0.268475,0.410147,-0.594288,0.591290,-0.242765,-0.188511,0
7829,0.895895,-0.653593,-0.020826,-0.981458,-0.152704,-0.549552,-0.688950,0.846517,0.389257,-0.101193,...,-0.765114,0.484713,0.046832,0.555670,0.067885,-0.759208,-0.306088,0.297535,0.296566,0
7830,0.843698,-0.749100,0.280108,-0.993174,-0.451919,-0.503397,-0.541013,0.661341,0.633278,0.213232,...,-0.641834,0.553275,0.042796,0.577361,0.525815,-0.402874,-0.080782,0.228377,-0.137405,0
7831,0.782707,-0.670501,-0.326957,-0.994221,-0.277875,-0.670175,-0.670645,0.747636,0.548301,0.354116,...,-0.876752,0.563466,0.137789,0.459504,0.385256,-0.566692,-0.363740,0.350959,0.175493,0
7832,0.744679,0.004101,0.444200,-0.697975,0.361724,-0.459923,-0.141900,0.974487,0.440359,-0.873953,...,-0.897368,-0.108110,-0.015679,-0.186226,0.234440,-0.650007,0.236022,0.451496,-0.114856,0

In [ ]:
from imblearn.pipeline import make_pipeline
from imblearn import datasets
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split, StratifiedKFold
from sklearn.metrics import recall_score, roc_auc_score, precision_score, f1_score, accuracy_score

import pandas as pd
import numpy as np

In [ ]:
#Divide train_data into input and target values
x4 = data1.drop("finaldiagnosis", axis = 1)
y4 = data1["finaldiagnosis"]
x4, y4

(           0         1         2         3         4         5         6    \
 0     0.075627  0.132981  0.128455  0.905081  0.991933  0.882216  0.631269
 1     0.874110 -0.512967  0.025296 -0.966775 -0.214251 -0.715966 -0.707653
 2     0.698588  0.467158  0.410709 -0.810982  0.029012  0.067626 -0.181474
 3     0.549374 -0.087779  0.800487  0.114196 -0.419980 -0.460071 -0.542703
 4     0.857971 -0.819153  0.020909 -0.989702 -0.163710 -0.552804 -0.746518
 ...        ...       ...       ...       ...       ...       ...       ...
 7828  0.552922 -0.030437  0.705118 -0.725346 -0.257711 -0.693921 -0.565398
 7829  0.895895 -0.653593 -0.020826 -0.981458 -0.152704 -0.549552 -0.688950
 7830  0.843698 -0.749100  0.280108 -0.993174 -0.451919 -0.503397 -0.541013
 7831  0.782707 -0.670501 -0.326957 -0.994221 -0.277875 -0.670175 -0.670645
 7832  0.744679  0.004101  0.444200 -0.697975  0.361724 -0.459923 -0.141900

            7         8         9    ...       758       759       760  \
 0     0.180067 -0.092080  0.405289  ...  0.086050  0.911581 -0.854586
 1     0.833488  0.349612 -0.205862  ... -0.409567 -0.831409  0.462622
 2     0.864893 -0.171834 -0.932124  ... -0.894625 -0.784692  0.330545
 3     0.911329 -0.320412 -0.951281  ... -0.857571 -0.649075 -0.422010
 4     0.656542  0.399067  0.645334  ... -0.055571 -0.858617  0.422339
 ...        ...       ...       ...  ...       ...       ...       ...
 7828  0.915197  0.452489 -0.804668  ... -0.911566 -0.753274 -0.084145
 7829  0.846517  0.389257 -0.101193  ...  0.097021 -0.765114  0.484713
 7830  0.661341  0.633278  0.213232  ... -0.274688 -0.641834  0.553275
 7831  0.747636  0.548301  0.354116  ...  0.185384 -0.876752  0.563466
 7832  0.974487  0.440359 -0.873953  ... -0.803021 -0.897368 -0.108110

            761       762       763       764       765       766       767
 0     0.648514  0.882056  0.490923 -0.781812 -0.398814 -0.883501 -0.442142
 1     0.314237  0.653831  0.257510 -0.805141 -0.339686  0.416634  0.151783
 2    -0.783493  0.477859  0.494536 -0.817453  0.619266  0.611336 -0.087373
 3     0.320293  0.490858  0.268078 -0.662021  0.235697 -0.013814 -0.249511
 4    -0.150346  0.591782  0.317968 -0.539443 -0.302800  0.774663  0.084319
 ...        ...       ...       ...       ...       ...       ...       ...
 7828 -0.484399  0.268475  0.410147 -0.594288  0.591290 -0.242765 -0.188511
 7829  0.046832  0.555670  0.067885 -0.759208 -0.306088  0.297535  0.296566
 7830  0.042796  0.577361  0.525815 -0.402874 -0.080782  0.228377 -0.137405
 7831  0.137789  0.459504  0.385256 -0.566692 -0.363740  0.350959  0.175493
 7832 -0.015679 -0.186226  0.234440 -0.650007  0.236022  0.451496 -0.114856

 [7833 rows x 768 columns],
 0       0
 1       0
 2       0
 3       0
 4       0
        ..
 7828    0
 7829    0
 7830    0
 7831    0
 7832    0
 Name: finaldiagnosis, Length: 7833, dtype: int64)

In [ ]:
# Neural Network #SMOTETomek Sampling
np.random.seed(0)
number_of_features= 768

#Create function returning a compiled network
def create_network():

    # Start neural network
    network = models.Sequential()

    # Add fully connected layer with a ReLU activation function
    network.add(layers.Dense(units=16, activation='relu', input_shape=(number_of_features,)))

    # Add fully connected layer with a ReLU activation function
    network.add(layers.Dense(units=16, activation='relu'))

    # Add fully connected layer with a sigmoid activation function
    network.add(layers.Dense(units=1, activation='sigmoid'))

    # Compile neural network
    network.compile(loss='binary_crossentropy', # Cross-entropy
                    optimizer='rmsprop', # Root Mean Square Propagation
                    metrics=['accuracy']) # Accuracy performance metric

    # Return compiled network
    return network

In [ ]:
# Wrap Keras model so it can be used by scikit-learn
from keras.wrappers.scikit_learn import KerasClassifier

neural_network = KerasClassifier(build_fn=create_network, epochs=10, batch_size=100, verbose=0)
neural_network._estimator_type = "classifier"

#neural_network._estimator_type = "classifier"
x_train, x_test, y_train, y_test = train_test_split(x4, y4, random_state=45)

# Evaluate neural network using 5-fold cross-validation
kf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)

example_params3 = {'batch_size':10, 'epochs':100}

params = {'batch_size': [10, 20, 40, 60, 80], 'epochs': [10, 20, 50, 100]}

# Evaluate model
def score_model(model, params, cv=None):
    if cv is None:
        cv = KFold(n_splits=5, random_state=42)

    smoter = SMOTETomek(random_state=42)

    scores1 = []
    scores2 = []
    scores3 = []
    scores4 = []
    scores5 = []


    for train_fold_index, val_fold_index in cv.split(x_train, y_train):
        x_train_fold, x_val_fold = x_train.iloc[train_fold_index], x_train.iloc[val_fold_index]
        y_train_fold, y_val_fold = y_train.iloc[train_fold_index], y_train.iloc[val_fold_index]

        x_train_fold_upsample, y_train_fold_upsample = smoter.fit_resample(x_train_fold, y_train_fold)

        model_obj = model.fit(x_train_fold_upsample, y_train_fold_upsample)

        score1 = recall_score(y_val_fold, model.predict(x_val_fold))
        score2 = precision_score(y_val_fold, model.predict(x_val_fold))
        score3 = f1_score(y_val_fold, model.predict(x_val_fold))
        score4 = roc_auc_score(y_val_fold, model.predict(x_val_fold))
        score5 = accuracy_score(y_val_fold, model.predict(x_val_fold))

        scores1.append(score1)
        scores2.append(score2)
        scores3.append(score3)
        scores4.append(score4)
        scores5.append(score5)

        dfnn1 = pd.DataFrame(scores1)
        dfnn2 = pd.DataFrame(scores2)
        dfnn3 = pd.DataFrame(scores3)
        dfnn4 = pd.DataFrame(scores4)
        dfnn5 = pd.DataFrame(scores5)

        dfnn11 = dfnn1.mean(axis=0)
        dfnn12 = dfnn2.mean(axis=0)
        dfnn13 = dfnn3.mean(axis=0)
        dfnn14 = dfnn4.mean(axis=0)
        dfnn15 = dfnn5.mean(axis=0)

    return dfnn11, dfnn12, dfnn13, dfnn14, dfnn15

# Example of the model in action
# print(type(neural_network))
score_model(neural_network, example_params3, cv=kf)

(0    0.104545
 dtype: float64,
 0    0.01946
 dtype: float64,
 0    0.032446
 dtype: float64,
 0    0.525279
 dtype: float64,
 0    0.937864
 dtype: float64)

In [ ]:
# Lets see how it compares to the test data
x_train_upsample, y_train_upsample = SMOTETomek(random_state=42).fit_resample(x_train, y_train)

neural_network.fit(x_train_upsample, y_train_upsample)

recalltest = recall_score(y_test, neural_network.predict(x_test))
precisiontest = precision_score(y_test, neural_network.predict(x_test))
f1test = f1_score(y_test, neural_network.predict(x_test))
roc_auctest = roc_auc_score(y_test, neural_network.predict(x_test))
accuracytest = accuracy_score(y_test, neural_network.predict(x_test))

recalltest, precisiontest, f1test, roc_auctest, accuracytest

(0.45, 0.06, 0.10588235294117647, 0.6886410520887055, 0.922409392547218)

In [ ]:
#No Oversampling
#How it compares to the test data
x_train_upsample, y_train_upsample = SMOTETomek(random_state=42).fit_resample(x_train, y_train)
neural_network.fit(x_train, y_train)

recalltest = recall_score(y_test, neural_network.predict(x_test))
precisiontest = precision_score(y_test, neural_network.predict(x_test))
f1test = f1_score(y_test, neural_network.predict(x_test))
roc_auctest = roc_auc_score(y_test, neural_network.predict(x_test))
accuracytest = accuracy_score(y_test, neural_network.predict(x_test))

recalltest, precisiontest, f1test, roc_auctest, accuracytest

/home/vmuser/anaconda3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

(0.0, 0.0, 0.0, 0.5, 0.9897907095456866)

In [ ]:
# Calculating the class weight
from sklearn.utils import compute_class_weight

class_weights = compute_class_weight("balanced",
                                    classes=np.unique(y_train),
                                    y=y_train)

class_weights

In [ ]:
#class_weight.compute_class_weight produces an array, we need to change it to a dict in order to work with Keras
class_weights = dict(enumerate(class_weights))
class_weights

In [ ]:
# Neural Network #Cost-Sensitive Classification
np.random.seed(0)
number_of_features= 768

#Create function returning a compiled network
def create_network1():

    # Start neural network
    network = models.Sequential()

    # Add fully connected layer with a ReLU activation function
    network.add(layers.Dense(units=16, activation='relu', input_shape=(number_of_features,)))

    # Add fully connected layer with a ReLU activation function
    network.add(layers.Dense(units=16, activation='relu'))

    # Add fully connected layer with a sigmoid activation function
    network.add(layers.Dense(units=1, activation='sigmoid'))

    # Compile neural network
    network.compile(loss='binary_crossentropy', # Cross-entropy
                    optimizer='rmsprop', # Root Mean Square Propagation
                    metrics=['accuracy']) # Accuracy performance metric

    # Return compiled network
    return network

In [ ]:
neural_network1 = KerasClassifier(build_fn=create_network1, epochs=10, batch_size=32, verbose=0)
neural_network1._estimator_type = "classifier"

# Use the same function above for the validation set
x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, test_size = 0.25,  stratify=y_train)


neural_network1.fit(x_train, y_train,
                               validation_data=(x_valid, y_valid),
                               epochs=10,
                               class_weight=class_weights)
recalltest = recall_score(y_test, neural_network1.predict(x_test))
precisiontest = precision_score(y_test, neural_network1.predict(x_test))
f1test = f1_score(y_test, neural_network1.predict(x_test))
roc_auctest = roc_auc_score(y_test, neural_network1.predict(x_test))
accuracytest = accuracy_score(y_test, neural_network1.predict(x_test))

recalltest, precisiontest, f1test, roc_auctest, accuracytest

NameError: name 'class_weights' is not defined

In [ ]:
recalltest = recall_score(y_test, neural_network1.predict(x_test))
precisiontest = precision_score(y_test, neural_network1.predict(x_test))
f1test = f1_score(y_test, neural_network1.predict(x_test))
roc_auctest = roc_auc_score(y_test, neural_network1.predict(x_test))
accuracytest = accuracy_score(y_test, neural_network1.predict(x_test))

recalltest, precisiontest, f1test, roc_auctest, accuracytest